/**
 * Mock food item data for demo mode.
 *
 * Each entry mirrors a Firestore "foods" document:
 *   id        – stable fake ID (never written to DB)
 *   name      – display name
 *   category  – "normal" | "goennung" | "drinks"
 *   grams     – portion in grams  (or null)
 *   liters    – portion in litres (or null)
 *   quantity  – portion as a count (or null)
 */

export const MOCK_FOODS = [
  // ── Normal ──────────────────────────────────────────────────────────────
  {
    id: "mf01",
    name: "Haferflocken",
    category: "normal",
    grams: 80,
    liters: null,
    quantity: null,
  },
  {
    id: "mf02",
    name: "Banane",
    category: "normal",
    grams: null,
    liters: null,
    quantity: 1,
  },
  {
    id: "mf03",
    name: "Apfel",
    category: "normal",
    grams: null,
    liters: null,
    quantity: 1,
  },
  {
    id: "mf04",
    name: "Vollkornbrot",
    category: "normal",
    grams: 60,
    liters: null,
    quantity: null,
  },
  {
    id: "mf05",
    name: "Hühnchenbrust",
    category: "normal",
    grams: 150,
    liters: null,
    quantity: null,
  },
  {
    id: "mf06",
    name: "Lachs",
    category: "normal",
    grams: 200,
    liters: null,
    quantity: null,
  },
  {
    id: "mf07",
    name: "Rührei",
    category: "normal",
    grams: null,
    liters: null,
    quantity: 2,
  },
  {
    id: "mf08",
    name: "Magerquark",
    category: "normal",
    grams: 250,
    liters: null,
    quantity: null,
  },
  {
    id: "mf09",
    name: "Pasta",
    category: "normal",
    grams: 100,
    liters: null,
    quantity: null,
  },
  {
    id: "mf10",
    name: "Brauner Reis",
    category: "normal",
    grams: 150,
    liters: null,
    quantity: null,
  },
  {
    id: "mf11",
    name: "Brokkoli",
    category: "normal",
    grams: 200,
    liters: null,
    quantity: null,
  },
  {
    id: "mf12",
    name: "Thunfisch",
    category: "normal",
    grams: 140,
    liters: null,
    quantity: null,
  },
  {
    id: "mf13",
    name: "Griechischer Joghurt",
    category: "normal",
    grams: 200,
    liters: null,
    quantity: null,
  },
  {
    id: "mf14",
    name: "Süßkartoffel",
    category: "normal",
    grams: 200,
    liters: null,
    quantity: null,
  },
  {
    id: "mf15",
    name: "Proteinriegel",
    category: "normal",
    grams: 65,
    liters: null,
    quantity: null,
  },
  {
    id: "mf16",
    name: "Magertopfen",
    category: "normal",
    grams: 200,
    liters: null,
    quantity: null,
  },
  {
    id: "mf17",
    name: "Hüttenkäse",
    category: "normal",
    grams: 150,
    liters: null,
    quantity: null,
  },
  {
    id: "mf18",
    name: "Linsensuppe",
    category: "normal",
    grams: 300,
    liters: null,
    quantity: null,
  },

  // ── Gönnung ─────────────────────────────────────────────────────────────
  {
    id: "mg01",
    name: "Schokolade",
    category: "goennung",
    grams: 30,
    liters: null,
    quantity: null,
  },
  {
    id: "mg02",
    name: "Chips",
    category: "goennung",
    grams: 50,
    liters: null,
    quantity: null,
  },
  {
    id: "mg03",
    name: "Eis",
    category: "goennung",
    grams: null,
    liters: null,
    quantity: 1,
  },
  {
    id: "mg04",
    name: "Kuchen",
    category: "goennung",
    grams: 120,
    liters: null,
    quantity: null,
  },
  {
    id: "mg05",
    name: "Pizza",
    category: "goennung",
    grams: 350,
    liters: null,
    quantity: null,
  },
  {
    id: "mg06",
    name: "Burger",
    category: "goennung",
    grams: null,
    liters: null,
    quantity: 1,
  },
  {
    id: "mg07",
    name: "Gummibärchen",
    category: "goennung",
    grams: 40,
    liters: null,
    quantity: null,
  },
  {
    id: "mg08",
    name: "Pommes",
    category: "goennung",
    grams: 150,
    liters: null,
    quantity: null,
  },

  // ── Drinks ──────────────────────────────────────────────────────────────
  {
    id: "md01",
    name: "Wasser",
    category: "drinks",
    grams: null,
    liters: 0.5,
    quantity: null,
  },
  {
    id: "md02",
    name: "Kaffee",
    category: "drinks",
    grams: null,
    liters: 0.3,
    quantity: null,
  },
  {
    id: "md03",
    name: "Tee",
    category: "drinks",
    grams: null,
    liters: 0.3,
    quantity: null,
  },
  {
    id: "md04",
    name: "Proteinshake",
    category: "drinks",
    grams: null,
    liters: 0.4,
    quantity: null,
  },
  {
    id: "md05",
    name: "Orangensaft",
    category: "drinks",
    grams: null,
    liters: 0.25,
    quantity: null,
  },
  {
    id: "md06",
    name: "Mineralwasser",
    category: "drinks",
    grams: null,
    liters: 0.75,
    quantity: null,
  },
];
